version: '3.8'
services:
  nginx:
    image: nginx:1.24
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"
      - "0.0.0.0:8443:8443"  # Added for SSL testing
    volumes:
      - /home/smcho/srv/www:/usr/share/nginx/html:ro
      - /home/smcho/srv/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - /home/smcho/srv/certbot/etc:/etc/letsencrypt:ro
      - /home/smcho/srv/certbot/www:/var/www/certbot:ro
    restart: always
    depends_on:
      - certbot
    networks:
      - nginx-net

  certbot:
    image: certbot/certbot
    volumes:
      - /home/smcho/srv/certbot/etc:/etc/letsencrypt
      - /home/smcho/srv/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  nginx-net:
    driver: bridge